# SwiftLint configuration for ModularHomeInventory

included:
  - Sources
  - Modules
  - HomeInventoryModular
  - Tests
  - UITests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - ${PWD}/Modules/*/Package.swift
  - ${PWD}/Modules/*/.build
  - ${PWD}/.build

# Rule configuration
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

# Opt-in rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  # - empty_count # Disabled due to false positives with count > 0 checks
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  # - fixme # Removed - not a valid rule
  - trailing_whitespace
  - vertical_whitespace
  - unused_optional_binding

# Custom rules
custom_rules:
  no_print_statements:
    name: "Print Statements"
    regex: '^\s*print\('
    match_kinds:
      - identifier
    message: "Use os_log or Logger instead of print statements"
    severity: warning

  marks_space:
    name: "MARK Format"
    regex: '//\s*MARK:[^\s]'
    message: "Add a space after MARK:"
    severity: warning

  no_direct_standard_out_logs:
    name: "Direct stdout logs"
    regex: 'NSLog\('
    match_kinds:
      - identifier
    message: "Use os_log or Logger instead of NSLog"
    severity: warning

# Naming rules
type_name:
  min_length: 3
  max_length: 50
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]

# SwiftUI specific
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true