name: HomeInventoryModular
options:
  bundleIdPrefix: com.homeinventory
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  groupSortPosition: bottom
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: 1.0.6
    CURRENT_PROJECT_VERSION: 7
    DEVELOPMENT_TEAM: "2VXBQV4XC9"
    SWIFT_VERSION: 5.9  # ⚠️ MUST use Swift 5.9 - DO NOT change to 6.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    ENABLE_PREVIEWS: YES
    CODE_SIGN_STYLE: Automatic
    SWIFT_STRICT_CONCURRENCY: minimal
    SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY: NO

packages:
  Core:
    path: Modules/Core
  SharedUI:
    path: Modules/SharedUI
  Items:
    path: Modules/Items
  BarcodeScanner:
    path: Modules/BarcodeScanner
  AppSettings:
    path: Modules/AppSettings
  Receipts:
    path: Modules/Receipts
  Sync:
    path: Modules/Sync
  Premium:
    path: Modules/Premium
  Onboarding:
    path: Modules/Onboarding
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.15.0

targets:
  HomeInventoryModular:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - Source
      - Supporting Files
      - Views
    dependencies:
      - package: Core
      - package: SharedUI
      - package: Items
      - package: BarcodeScanner
      - package: AppSettings
      - package: Receipts
      - package: Sync
      - package: Premium
      - package: Onboarding
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homeinventory.app
        DEVELOPMENT_TEAM: "2VXBQV4XC9"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleDisplayName: "Home Inventory"
        INFOPLIST_KEY_NSCameraUsageDescription: "Camera access is needed to scan barcodes and take photos of your items"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        # Encryption Export Compliance
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: YES
        INFOPLIST_KEY_ITSEncryptionExportComplianceCode: "ecf076d3-130b-4b7d-92e0-6a69e07b5b6d"
  
  HomeInventoryModularTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - HomeInventoryModularTests
    dependencies:
      - target: HomeInventoryModular
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homeinventory.modular.tests
        DEVELOPMENT_TEAM: "2VXBQV4XC9"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        HOST_APPLICATION: HomeInventoryModular
  
  HomeInventoryModularUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - HomeInventoryModularUITests
    dependencies:
      - target: HomeInventoryModular
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.homeinventory.modular.uitests
        DEVELOPMENT_TEAM: "2VXBQV4XC9"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: HomeInventoryModular