#!/bin/bash

echo "🔍 App Store Connect API Helper"
echo "==============================="
echo ""
echo "Your API Key Details:"
echo "- Key ID: R8379S36V8"
echo "- Team ID: 2VXBQV4XC9"
echo "- App ID: 6747408377"
echo ""
echo "To find your Issuer ID:"
echo "1. You're already in App Store Connect"
echo "2. Look at the very TOP of the Keys page (above your key list)"
echo "3. You should see: 'Issuer ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'"
echo ""
echo "It's NOT your Team ID (2VXBQV4XC9)"
echo "It's a longer UUID that identifies your API account"
echo ""
echo "Once you have it, you can check your build with:"
echo ""
echo "xcrun altool --list-apps \\"
echo "    --apiKey R8379S36V8 \\"
echo "    --apiIssuer YOUR_ISSUER_ID_HERE"
echo ""
echo "Or I can create a direct API call to check build status."
echo ""
echo "Based on your Transporter upload:"
echo "✅ Build 1.0.6 (9) was uploaded at 03:32 AM"
echo "⏳ Currently processing (started ~30 minutes ago)"
echo "📧 Check your email for processing completion"
echo ""
echo "The build should be ready by now!"